import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HeaderComponent } from '../header/header.component';
import { FooterComponent } from '../footer/footer.component';

@Component({
  selector: 'app-services',
  standalone: true,
  imports: [CommonModule, RouterModule, HeaderComponent, FooterComponent],
  templateUrl: './services.component.html',
  styleUrls: ['./services.component.scss']
})
export class ServicesComponent {
  services = [
    {
      image: 'assets/img/services/services-1.jpg',
      title: 'AI-Powered Workout Plans',
      description: 'Get personalized workout plans generated by AI based on your goals, physical condition, and preferences for optimal results.',
      order: 1
    },
    {
      image: 'assets/img/services/services-2.jpg',
      title: 'Expert Coach Connection',
      description: 'Connect with certified fitness professionals who will guide you through your fitness journey with personalized attention and expertise.',
      order: 2
    },
    {
      image: 'assets/img/services/services-3.jpg',
      title: 'Progress Tracking',
      description: 'Monitor your fitness journey with detailed progress tracking tools, helping you stay motivated and achieve your goals effectively.',
      order: 3
    },
    {
      image: 'assets/img/services/services-4.jpg',
      title: 'Real-time Communication',
      description: 'Stay connected with your coach through our seamless communication platform for instant feedback and support.',
      order: 4
    }
  ];

  pricingPlans = [
    {
      title: 'Free Plan',
      price: 0,
      period: 'PERMANENTLY FREE',
      features: [
        'Track workouts and nutrition',
        'Access to AI-powered personalized workout plans',
        'Plans tailored to your goals and preferences',
        'Basic progress tracking',
        'Community support',
        'No time restrictions'
      ]
    },
    {
      title: 'Coach Plan',
      price: 'Varies',
      period: 'SUBSCRIPTION',
      features: [
        'Everything in Free Plan',
        'One-on-one coach support',
        'Progress monitoring & feedback',
        'Customized workout adjustments',
        'Nutrition guidance',
        'Priority support'
      ]
    }
  ];

  showSearch = false;

  toggleSearch() {
    this.showSearch = !this.showSearch;
  }

  onSearchSubmit(event: Event) {
    event.preventDefault();
    // Handle search submission
  }
}
